remote_theme: thuhcsi/slate
title: "LightGrad: Lightweight Diffusion Probabilistic Model for Text-to-speech"
description: Accepted by ICASSP2023. Code is available at https://github.com/thuhcsi/LightGrad/ .